### PR TITLE
MoveIt Package for MH5 + PGN64

### PR DESCRIPTION
**Pull request by acbuynak**
Generate MoveIt package for MH5 with the PGN64 parallel grippers.
Built using the [moveit_setup_assistant](http://docs.ros.org/melodic/api/moveit_tutorials/html/doc/setup_assistant/setup_assistant_tutorial.html) and ontop of the xacro wrapper in the [schunk_pgn64_support]() package.

Gripper added as an extension of final link_t. Singular kinematic chain. Single Planning Group.
Did NOT implement as an eef (end effector) within MoveIt. Experimented with this but proved to be fairly difficult without minimal to no benefit to future use. This is because the PGN64 is an open loop control and the MoveIt requires closed loop. 

**Included Group States:**
Format --- `[ s l u r b t ]`
Default: `[ 0 0 0 0 0 0 ]`
Home: `[ 0 -0.7 -0.69 0 -1.58 0 ]`
Vertical: `[ 0 0 1.57 0 0 0 ]`

**Config Details:**
Robot name: "bot_mh5"
Planning group name: "mh5_arm"

**Notes:**
Added a small 'ball' at the eef TCP (tool center point) for visualization and allow interactive markers to be visible.

**Potential Issue**
Interactive Markers do not appear when no geometry (visual or collision) is provided in the URDF. This is why the small ball was added at the TCP

### CODE REVIEW

**Comment by acbuynak** [comment]
**To-Do prior to Merge:**
Need to add configuration files that allow connection of MoveIt package with MotoRos for control of physical MH5 robot.

**Comment by hansen95** [comment]
Navigated to ~/ws_dev_io/src where .git folder exists.
Entered
  git fetch origin pull/7/head:pull_7
Got
  fatal: Couldn't find remote ref pull/7/head

**Comment by hansen95** [comment]
Git commands worked once I changed to ~/ws_core/src 
After roslaunch moveit_mh5_pgn64_config moveit_planning_execution.launch sim:=false robot_ip:=10.0.0.2 controller:=fs100

Terminal streams these errors continuously:
[ERROR] [1588960208.849471937]: Joint 'joint_s' not found in model 'bot_mh5'
[ERROR] [1588960208.849519751]: Joint 'joint_l' not found in model 'bot_mh5'
[ERROR] [1588960208.849543648]: Joint 'joint_u' not found in model 'bot_mh5'
[ERROR] [1588960208.849567178]: Joint 'joint_r' not found in model 'bot_mh5'
[ERROR] [1588960208.849590637]: Joint 'joint_b' not found in model 'bot_mh5'
[ERROR] [1588960208.849612276]: Joint 'joint_t' not found in model 'bot_mh5'

Rviz launches and gripper geometry looks right, but can no longer move the robot from Rviz. Can still enable robot and read/write IO.

**Comment by acbuynak** [comment]
I think my own unfamiliarity with 'git' is the root issue based on the commands I have you.

> Entered
>   git fetch origin pull/7/head:pull_7
> Got
>   fatal: Couldn't find remote ref pull/7/head

In the above we used the `head` instruction when pulling from origin instead of `merge`. This should have pulled everything down and not just changes. 

My guess is that not all the components needed got merged into the new segment of code.

--

I'd suggest erasing the entire directory contents or starting a new directory. Either way, ensure that the .git hidden folder is wiped. Create a new src folder with `mkdir`. Navigate into this folder with `cd`
Then reinitialize git with command `git init`
Set the remote: `git remote add origin https://github.com/osu-aims/aims_core.git`

Intialize the catkin_tools with: `catkin init`

Pull the Pull Request #7:
`git fetch origin pull/7/head:pull_7`
`git checkout pull_7`

Then test the same commands from earlier.

**Comment by hansen95** [comment]
Did this:
```
mkdir -p ws_core_test/src
cd ws_core_test/src
git init
git remote add origin https://github.com/osu-aims/aims_core.git
git fetch origin pull/7/head:pull_7
git checkout pull_7
cd ..
catkin init
catkin clean
catkin build
source devel/setup.bash
roscore
<new terminal>
source devel/setup.bash
<change to robot network>
roslaunch moveit_mh5_pgn64_config moveit_planning_execution.launch sim:=false robot_ip:=10.0.0.2 controller:=fs100
```
I tried several times, always getting a constant stream of errors:
[ERROR] [1589152603.514326386]: Joint 'joint_s' not found in model 'bot_mh5'
[ERROR] [1589152603.514378527]: Joint 'joint_l' not found in model 'bot_mh5'
[ERROR] [1589152603.514404824]: Joint 'joint_u' not found in model 'bot_mh5'
[ERROR] [1589152603.514425419]: Joint 'joint_r' not found in model 'bot_mh5'
[ERROR] [1589152603.514444498]: Joint 'joint_b' not found in model 'bot_mh5'
[ERROR] [1589152603.514465215]: Joint 'joint_t' not found in model 'bot_mh5'

Rviz opens, and after changing base frame from base_link to robot_base_link, Global Status becomes Ok.
`rosservice call robot_enable` works, but I can't move the robot from the Planning window, and the robot state is not correct (position in Rviz does not match actual robot position).

**Comment by acbuynak** [comment]
Okay. Thanks for the update.
I've been working on this issue and I think it may be due to me combining URDF/macros using a macro script, but unsure yet.

I'm waiting to get my VM up and running again, but will follow-up here when I have a fix.

**Comment by acbuynak** [comment]
Okay. I was unable to recreate the issue that you identified, but I think I isolated the issue as a mismatched naming convention.

My best guess is that when I created the macro to combine the robot arm with the schunk eef, I assigned a prefix of "robot_" or "eef_" to each joint/link in the kinematic chain. Thought this would be good practice for future work, but nonessential at the moment. 

I think when the moveit package connects with the motoman controller, it looks for the standard motoman joint naming of "joint_s" which will not match my renamed "robot_joint_s". If an issue with the actual motoman controller, I don't _think_ I can test that error. The latest commit renames these joints/links.

Commit 36943c6 should fix all the issues mentioned. Notes are included on the commit as to what changed.

**Comment by hansen95** [comment]
It works! I was able to move the robot from Rviz and those repeating error messages are gone. Well done!

Some output you might be interested to see:
`[ INFO] [1589234829.865290750]: Loading robot model 'bot_mh5'...
[ WARN] [1589234829.865345991]: Skipping virtual joint 'FixedBase' because its child frame 'base_link' does not match the URDF frame 'world'
[ INFO] [1589234829.865368314]: No root/virtual joint specified in SRDF. Assuming fixed joint
[ WARN] [1589234829.931894861]: Kinematics solver doesn't support #attempts anymore, but only a timeout.
Please remove the parameter '/rviz_aims_zaphod_8011_4183648831523090461/mh5_arm/kinematics_solver_attempts' from your configuration.
[ INFO] [1589234830.143883270]: Starting planning scene monitor
[ INFO] [1589234830.146058135]: Listening to '/move_group/monitored_planning_scene'
[ INFO] [1589234830.581121094]: Constructing new MoveGroup connection for group 'mh5_arm' in namespace ''
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
[ INFO] [1589234831.781041870]: Ready to take commands for planning group mh5_arm.
[ INFO] [1589234831.781144386]: Looking around: no
[ INFO] [1589234831.781232937]: Replanning: no
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
QAbstractItemView::setSelectionModel() failed: Trying to set a selection model, which works on a different model than the view.
`

**Comment by acbuynak** [comment]
I haven't been able to find much info on this warning or identify where it originates from but one suggestion I found was to...

Remove shiboken with `sudo apt-get remove libshiboken*`
and then re-run the build.

This may introduce numerous other errors if there are multiple dependencies on `libshiboken`
Reinstall with `sudo apt-get install libshiboken`

*Note: I do not fully understand what this library does.

@hansen95  If you we are otherwise good with this PR, please approve the review and I will close/merge the PR.

**Pull request merged**
